Fix build for removal of firefox-{beta,devedition}-bin from nixpkgs
error: function 'anonymous lambda' called with unexpected argument 'channel'
at /nix/store/ny8c07vsrfwcb1c4i3jcpbi3qi4w9wy6-source/pkgs/applications/networking/browsers/firefox-bin/default.nix:1:1

https://github.com/NixOS/nixpkgs/pull/414510

Signed-off-by: Anders Kaseorg <andersk@mit.edu>